name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    # Step to checkout the source code
    - name: Checkout
      uses: actions/checkout@v4
      
    # Step to set up QEMU for multi-architecture builds
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    # Step to set up Docker Buildx for extended build capabilities
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    # Step to log in to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    # Step to build and push your Docker image
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/arm64
        push: true
        tags: 0xaccretion/cardano-node-arm64-1-35-7:${{ github.sha }}

    
